### ISSUE TITLE
What criteria do you use to select the providers you want to integrate by default?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/switchboard-plug-onlineaccounts#116]
Related to the selection that can be found here:
https://github.com/elementary/switchboard-plug-onlineaccounts/tree/master/providers

**Comment by tintou** [comment]
First criteria: people wanting to work on it

**Comment by 4jNsY6fCVqZv** [comment]
1. In that case, the list could become endless, couldn't it? How difficult is providing an integration?
2. Couldn't you as a team also draw people's attention to ethical alternatives through the pre-selection you make? For example Open Source, especially security an/or data protection oriented etc. ...

**Comment by cassidyjames** [comment]
Second criteria: apps integrating with them. We won't make requirements around the providers so much because integrating with the online accounts that users already use is a huge migration path to being able to use elementary OS and the other ethical, open source software on the platform. If all we support is open source services, we're creating a bubble that's separated from most potential users' reality.

I'm closing this issue since it is not really actionable, but I'm happy to discuss it further.

**Comment by 4jNsY6fCVqZv** [comment]
Yeah, that ticket was more like a question. In what context would you like to discuss it further?

Of course, my idea was not to promote a bubble. But not only to pick up the users where they stand, but also to give them ideas and suggestions for free solutions that correspond to such strong ethical values as I have started to collect above.

**Comment by 4jNsY6fCVqZv** [comment]
Yeah, that ticket was more like a question. In what context would you like to discuss it further?

My idea would be to pick up the users where they stand, as you describe it. And to offer them additional, alternative solutions that promote strong values, as I have tried to outline above. Not in the sense of a bubble and not as strict minimum requirements for new providers in the list, but as impulses for a better world.
