### ISSUE TITLE
Add a setting to allow the user to configure the interval to fetch new email

### ISSUE THREAD

**Issue by casasfernando** [elementary/switchboard-plug-onlineaccounts#223]
## Problem
At the moment is not possible to know or change the default interval to check for new emails.

## Proposal
Add a setting to allow the user to configure the interval to fetch new email. It can have a few default interval options (1 min, 5 mins, 10 mins, 30 mins, hourly, Manually)  and a custom one for the user to define any value he wants (15 mins or any other value).

## Prior Art
In Apple iOS there in Settings -> Mail -> Accounts -> Fetch New Data in the "Fetch" section the user can configure the desired value for the interval to automatically fetch new emails.

**Comment by marbetschar** [comment]
This would require to have https://github.com/elementary/switchboard-plug-onlineaccounts/pull/222 merged - then we can make it configurable in the UI.

Please note you can configure said value in the accounts settings of Evolution for now. But I don't think it has any effect for now. Since the only place I'm aware of where this is used is in https://github.com/elementary/mail/pull/679 - which is not merged atm.

**Comment by casasfernando** [comment]
Quick question, a bit unrelated, @marbetschar should I install Evolution from deb packages or installing the flatpak from flathub should also work?
I'm asking because I tried to install the flatpak from flathub just to play around with this settings, but none of my IMAP accounts nor the CalDAV account I configured in online accounts was visible to it.

**Comment by marbetschar** [comment]
@casasfernando you need to install Evolution from deb packages to be able to tinker with such system settings stuff. If you install as Flatpack it wont work as  you experienced it, because it is sandboxed.

**Comment by casasfernando** [comment]
Got it. Thanks!

**Comment by kalmbach** [comment]
Related https://github.com/elementary/mail/issues/752
